# Postgres configuration
#   gem install pg
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: 
  host: localhost
  port: 5432

development:
  <<: *default
  database: hash_stone_development

test:
  <<: *default
  database: hash_stone_test
